version: '3'
services:
  postgres-db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:z
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/graphql
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db